# Generated by Django 5.2 on 2025-07-09 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('hectareas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caravana', models.CharField(max_length=50, unique=True)),
                ('raza', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_ingreso', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dosis', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganado.vacuna')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='ganado.vacuno')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('campo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada', to='ganado.campo')),
                ('campo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_salida', to='ganado.campo')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganado.vacuno')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVacuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ciclo_productivo', models.CharField(blank=True, choices=[('ternero', 'Ternero'), ('novillo', 'Novillo'), ('toro', 'Toro'), ('ternera', 'Ternera'), ('vaquillona', 'Vaquillona'), ('vaca', 'Vaca')], help_text='ternero/novillo/toro o ternera/vaquillona/vaca según sexo', max_length=20)),
                ('estado_salud', models.CharField(blank=True, choices=[('sano', 'Sano'), ('brucelosis', 'Brucelosis'), ('tuberculosis', 'Tuberculosis'), ('otra', 'Otra')], max_length=20)),
                ('estado_general', models.CharField(blank=True, choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('muerto', 'Muerto'), ('transferido', 'Transferido')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('vacuno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='ganado.vacuno')),
            ],
        ),
        migrations.CreateModel(
            name='EstadiaAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganado.campo')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='ganado.vacuno')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comprador', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('destino', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganado.vacuno')),
            ],
        ),
    ]
