# Generated by Django 5.2.4 on 2025-08-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuno',
            name='caravana',
        ),
        migrations.AddField(
            model_name='vacuno',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de animales en el lote'),
        ),
        migrations.AddField(
            model_name='vacuno',
            name='lote_id',
            field=models.CharField(default='LOTE-001', help_text='Identificador del lote', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacuno',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
