# Generated by Django 5.2 on 2025-07-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadovacuno',
            options={'ordering': ['-fecha'], 'verbose_name': 'Estado del Vacuno', 'verbose_name_plural': 'Estados de Vacunos'},
        ),
        migrations.AlterModelOptions(
            name='preciomercado',
            options={'ordering': ['-fecha'], 'verbose_name': 'Precio de Mercado', 'verbose_name_plural': 'Precios de Mercado'},
        ),
        migrations.AlterUniqueTogether(
            name='preciomercado',
            unique_together={('fecha', 'categoria')},
        ),
    ]
