databases:
  - name: gestion-agro-db
    plan: free

services:
  - type: web
    name: gestion-agro-backend
    plan: free
    env: docker
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1
      - key: FRONTEND_URL
        value: https://<tu-frontend>
      - key: CORS_ALLOWED_ORIGINS
        value: https://<tu-frontend>,http://localhost:5173
      - key: CSRF_TRUSTED_ORIGINS
        value: https://gestion-agro-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-agro-db
          property: connectionString

  - type: web
    name: gestion-agro-frontend
    plan: free
    env: docker
    dockerfilePath: frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE_URL
        value: https://gestion-agro-backend.onrender.com/api
