databases:
  - name: gestion-agro-db
    plan: free

services:
  - type: web
    name: gestion-agro
    plan: free
    env: docker
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    healthCheckPath: /health/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:5173,http://127.0.0.1:5173
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-agro-db
          property: connectionString
